version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: script/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: script/start.sh
      runas: ec2-user
      timeout: 60
      runas: ec2-user
