version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package -Dmaven.test.skip=true
artifacts:
  files:
    - yudao-server/target/yudao-server.jar  
    - appspec.yml
    - script/**
